
name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 6 * * *' # Runs daily at 6:05am UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install

      - name: Deploy to Cloudflare
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}